# Generated by Django 4.2.27 on 2026-01-14 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maliyet')),
                ('my_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatım')),
                ('min_price_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min. Fiyat Limiti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Rakip Linki')),
                ('marketplace_name', models.CharField(max_length=100, verbose_name='Pazaryeri (Trendyol/Amazon)')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Güncel Fiyat')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Stokta Var mı?')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='core.product', verbose_name='Bağlı Ürün')),
            ],
            options={
                'verbose_name': 'Rakip',
                'verbose_name_plural': 'Rakipler',
            },
        ),
    ]
